apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-production
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: patch-replicas.yaml
images:
  - name: ghcr.io/example/gitops-demo
    newTag: v1.0.0
